name: group_maker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  janray_flutter_kit:
    git: 
      url: git@github.com:JanrayCausaren/janray_flutter_kit.git
      ref: v1.0.0

  flutter:
    sdk: flutter

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
