// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:group_maker/core/enums/enums.dart';
import 'package:group_maker/features/directories/data/models/directory_hive_model.dart';
import 'package:group_maker/features/directories/data/models/members_directory_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DirectoryHiveModelAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(MembersDirectoryHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DirectoryHiveModelAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(MembersDirectoryHiveModelAdapter());
  }
}
